version = 0.1

[default.deploy.parameters]
stack_name = "switchbot-meter-database"
resolve_s3 = true
s3_prefix = "switchbot-meter-database"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Database=\"\" SwitchbotToken=\"\" SwitchbotSecret=\"\" MongoDBUri=\"\" MongoDBDatabase=\"\" MongoDBCollection=\"\" MongoDBUsername=\"\" MongoDBPassword=\"\""
image_repositories = []
