AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: !Ref Runtime

Parameters:
  Runtime:
    Type: String
    Default: python3.12
    Description: The runtime of the Lambda function
  Architecture:
    Type: String
    Default: arm64
    Description: The architecture of the Lambda function
  Database:
    Type: String
  SwitchbotToken:
    Type: String
  SwitchbotSecret:
    Type: String
  MongoDBUri:
    Type: String
  MongoDBDatabase:
    Type: String
  MongoDBCollection:
    Type: String
  MongoDBUsername:
    Type: String
  MongoDBPassword:
    Type: String

Resources:
  SwitchBotDatabase:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: !Ref Runtime
      Architectures:
        - !Ref Architecture
      Handler: lambda.handler
      Timeout: 30
      CodeUri: src/
      Environment:
        Variables:
          DATABASE: !Ref Database
          SWITCHBOT_TOKEN: !Ref SwitchbotToken
          SWITCHBOT_SECRET: !Ref SwitchbotSecret
          MONGODB_URI: !Ref MongoDBUri
          MONGODB_DATABASE: !Ref MongoDBDatabase
          MONGODB_COLLECTION: !Ref MongoDBCollection
          MONGODB_USERNAME: !Ref MongoDBUsername
          MONGODB_PASSWORD: !Ref MongoDBPassword
      # Events:
      #   ScheduledEvent:
      #     Type: Schedule
      #     Properties:
      #       Schedule: rate(5 minutes)
      Layers:
        - !Ref SwitchBotDatabaseDependenciesLayer

  # Lambda Layer
  SwitchBotDatabaseDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: lambda_layer
      CompatibleRuntimes:
        - !Ref Runtime
      CompatibleArchitectures:
        - !Ref Architecture
      Description: Python packages for Lambda functions.
    Metadata:
      BuildMethod: !Ref Runtime
      BuildArchitecture: !Ref Architecture

  # CloudWatch Logs
  SwitchBotDatabaseLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${SwitchBotDatabase}
      RetentionInDays: 30
