AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: !Ref Runtime

Parameters:
  Runtime:
    Type: String
    Default: python3.12
    Description: The runtime of the Lambda function
  Architecture:
    Type: String
    Default: arm64
    Description: The architecture of the Lambda function
  AWSParametersAndSecretsLambdaExtension:
    Type: String
    Default: arn:aws:lambda:ap-northeast-1:133490724326:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:19
    Description: AWS Parameters and Secrets Lambda Extension
  SwitchbotTokenParamName:
    Type: String
    Default: /switchbot-meter-database/switchbot-token
  SwitchbotSecretParamName:
    Type: String
    Default: /switchbot-meter-database/switchbot-secret
  DatabaseParamName:
    Type: String
    Default: /switchbot-meter-database/database
  MongoDBUriParamName:
    Type: String
    Default: /switchbot-meter-database/mongodb-uri
  MongoDBDatabaseParamName:
    Type: String
    Default: /switchbot-meter-database/mongodb-database
  MongoDBCollectionParamName:
    Type: String
    Default: /switchbot-meter-database/mongodb-collection

Resources:
  SwitchBotDatabase:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: !Ref Runtime
      Architectures:
        - !Ref Architecture
      Handler: lambda.handler
      CodeUri: src/
      Layers:
        - !Ref SwitchBotDatabaseDependenciesLayer
        - !Ref AWSParametersAndSecretsLambdaExtension
      Environment:
        Variables:
          DATABASE_PATH: !Ref DatabaseParamName
          SWITCHBOT_TOKEN_PATH: !Ref SwitchbotTokenParamName
          SWITCHBOT_SECRET_PATH: !Ref SwitchbotSecretParamName
          MONGODB_URI_PATH: !Ref MongoDBUriParamName
          MONGODB_DATABASE_PATH: !Ref MongoDBDatabaseParamName
          MONGODB_COLLECTION_PATH: !Ref MongoDBCollectionParamName
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - 'ssm:GetParameter'
              Resource:
                - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${SwitchbotTokenParamName}'
                - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${SwitchbotSecretParamName}'
                - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${DatabaseParamName}'
                - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${MongoDBUriParamName}'
                - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${MongoDBDatabaseParamName}'
                - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${MongoDBCollectionParamName}'
            - Effect: Allow
              Action:
                - 'kms:Decrypt'
              Resource: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/ssm"
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0/5 * * * ? *)

  # Lambda Layer
  SwitchBotDatabaseDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: lambda_layer
      CompatibleRuntimes:
        - !Ref Runtime
      CompatibleArchitectures:
        - !Ref Architecture
      Description: Python packages for Lambda functions.
    Metadata:
      BuildMethod: !Ref Runtime
      BuildArchitecture: !Ref Architecture

  # CloudWatch Logs
  SwitchBotDatabaseLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${SwitchBotDatabase}
      RetentionInDays: 30
